# Generated by Django 5.0.2 on 2024-04-03 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='publishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='avatar/%Y/%m/%d')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books/%Y/%m/%d')),
                ('name_book', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('series', models.CharField(max_length=255)),
                ('year_publishing', models.IntegerField()),
                ('file_book', models.FileField(upload_to='file_books/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category')),
                ('publishing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.publishing')),
            ],
        ),
        migrations.CreateModel(
            name='in_planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.users')),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.users')),
            ],
        ),
    ]
